#!/bin/bash

# GitAgent SSH 终端部署系统 - 帮助脚本
# 显示所有可用命令和使用说明

echo "📚 GitAgent SSH 终端部署系统 - 帮助文档"
echo "=========================================="

echo ""
echo "🎯 快速开始"
echo "=========="
echo "1. 环境检查: ./deploy/sh/check-env.sh"
echo "2. 安装依赖: ./deploy/sh/install.sh"
echo "3. 启动服务: ./deploy/sh/start.sh"
echo "4. 访问应用: http://localhost:5173"
echo ""

echo "📋 可用命令"
echo "=========="
echo "🔍 check-env.sh  - 检查环境配置 (Node.js、npm、依赖等)"
echo "📦 install.sh    - 安装项目依赖和配置环境"
echo "🚀 start.sh      - 启动前端和SSH代理服务"
echo "🛑 stop.sh       - 停止所有服务"
echo "🔄 restart.sh    - 重启所有服务"
echo "📊 status.sh     - 查看服务运行状态"
echo "📝 logs.sh       - 查看和管理日志文件"
echo "❓ help.sh       - 显示此帮助信息"
echo ""

echo "🌐 服务地址"
echo "=========="
echo "前端应用:     http://localhost:5173"
echo "SSH代理服务:  http://localhost:3001"
echo ""

echo "🔧 系统要求"
echo "=========="
echo "• Node.js v16+"
echo "• npm v8+"
echo "• 端口 5173 和 3001 可用"
echo ""

echo "📁 目录结构"
echo "=========="
echo "deploy/sh/     - 部署脚本目录"
echo "logs/         - 日志文件目录"
echo "src/          - 源代码目录"
echo "node_modules/ - 依赖包目录"
echo ""

echo "🔍 故障排除"
echo "=========="
echo "1. 端口被占用: 运行 stop.sh 停止服务，或手动释放端口"
echo "2. 依赖问题: 运行 install.sh 重新安装依赖"
echo "3. 权限问题: 确保脚本有执行权限 (chmod +x deploy/sh/*.sh)"
echo "4. 日志查看: 运行 logs.sh 查看详细错误信息"
echo ""

echo "📝 使用示例"
echo "=========="
echo "# 首次部署"
echo "./deploy/sh/check-env.sh"
echo "./deploy/sh/install.sh"
echo "./deploy/sh/start.sh"
echo ""
echo "# 日常使用"
echo "./deploy/sh/start.sh    # 启动服务"
echo "./deploy/sh/status.sh   # 查看状态"
echo "./deploy/sh/logs.sh     # 查看日志"
echo "./deploy/sh/stop.sh     # 停止服务"
echo ""

echo "🔐 安全说明"
echo "=========="
echo "• SSH私钥仅在浏览器本地处理"
echo "• 所有SSH通信通过本地代理服务器进行"
echo "• 会话结束后自动清理敏感数据"
echo ""

echo "📞 技术支持"
echo "=========="
echo "如果遇到问题，请检查："
echo "1. Node.js版本是否为v16+"
echo "2. 端口5173和3001是否被占用"
echo "3. 防火墙是否阻止了相关端口"
echo "4. 网络连接是否正常"
echo "5. 查看日志文件获取详细错误信息"
echo ""

echo "🎉 祝您使用愉快！" 